# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 06:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20171030_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=32)),
                ('author', models.CharField(max_length=32)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('publish_date', models.DateField()),
                ('authorlist', models.ManyToManyField(related_name='booklist', to='app01.Author')),
                ('publish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booklist', to='app01.Publish')),
            ],
        ),
    ]
